import { z, type ZodSchema } from "zod";
import type { Capability } from "./rbac";
import {
  contactCreate, contactUpdate,
  companyCreate, companyUpdate,
  opportunityCreate, opportunityUpdate,
  visitCreate, visitUpdate, measurementCreate,
  finishCreate, finishUpdate,
  sampleCreate, sampleUpdate,
  projectCreate, projectUpdate,
  taskCreate, taskUpdate,
  changeOrderCreate,
  eventCreate, eventUpdate,
  supplierCreate, supplierUpdate,
  materialCreate, materialUpdate,
  expenseCreate, expenseUpdate,
  paymentCreate,
  activityCreate,
  commentCreate,
  serviceTypeCreate,
} from "./schemas";

export type ResourceConfig = {
  model: string;
  capView: Capability;
  capEdit: Capability;
  capDelete?: Capability;
  softDelete?: boolean;
  searchFields: string[];
  /** Explicitly allowed equality filters and their URL coercion type. */
  filterFields?: Record<string, "string" | "boolean" | "number">;
  orderBy?: Record<string, "asc" | "desc">;
  createSchema: ZodSchema;
  updateSchema: ZodSchema;
  includeDetail?: Record<string, unknown>;
  /** Fields only visible to privileged roles */
  sensitiveFields?: string[];
  sensitiveCapability?: Capability;
};

// Never include a Prisma User relation wholesale: that also serializes
// passwordHash, hourlyRate, lastLoginAt, and other account-only fields.
const relatedUser = {
  select: { id: true, firstName: true, lastName: true, color: true, role: true },
};

export const RESOURCES: Record<string, ResourceConfig> = {
  contacts: {
    model: "contact",
    capView: "contacts.view",
    capEdit: "contacts.edit",
    capDelete: "contacts.delete",
    softDelete: true,
    searchFields: ["firstName", "lastName", "email", "phone", "mobile", "city"],
    filterFields: { businessType: "string", region: "string", companyId: "string", ownerId: "string" },
    orderBy: { lastName: "asc" },
    createSchema: contactCreate,
    updateSchema: contactUpdate,
    includeDetail: { company: true, owner: relatedUser },
  },
  companies: {
    model: "company",
    capView: "companies.view",
    capEdit: "companies.edit",
    capDelete: "companies.delete",
    softDelete: true,
    searchFields: ["name", "vatNumber", "city", "email"],
    filterFields: { businessType: "string" },
    orderBy: { name: "asc" },
    createSchema: companyCreate,
    updateSchema: companyUpdate,
  },
  opportunities: {
    model: "opportunity",
    capView: "pipeline.view",
    capEdit: "pipeline.edit",
    capDelete: "pipeline.delete",
    softDelete: true,
    searchFields: ["title", "projectName", "city", "requestedFinish"],
    filterFields: { stage: "string", contactId: "string", companyId: "string", assignedUserId: "string" },
    orderBy: [{ position: "asc" }, { updatedAt: "desc" }] as never,
    createSchema: opportunityCreate,
    updateSchema: opportunityUpdate,
    includeDetail: { contact: true, company: true, assignedTo: relatedUser, serviceTypeRef: true },
    sensitiveFields: ["internalNotes"],
    sensitiveCapability: "pipeline.edit",
  },
  visits: {
    model: "siteVisit",
    capView: "visits.view",
    capEdit: "visits.edit",
    capDelete: "visits.delete",
    softDelete: true,
    searchFields: ["title", "address", "city"],
    filterFields: { status: "string", contactId: "string", opportunityId: "string", assignedUserId: "string" },
    orderBy: { scheduledAt: "desc" },
    createSchema: visitCreate,
    updateSchema: visitUpdate,
    includeDetail: { contact: true, opportunity: true, assignedTo: relatedUser, _count: { select: { measurements: true } } },
  },
  measurements: {
    model: "measurement",
    capView: "visits.view",
    capEdit: "visits.edit",
    searchFields: ["areaName"],
    filterFields: { visitId: "string" },
    createSchema: measurementCreate,
    updateSchema: measurementCreate.partial(),
  },
  finishes: {
    model: "finish",
    capView: "catalogue.view",
    capEdit: "catalogue.edit",
    softDelete: true,
    searchFields: ["code", "nameEl", "nameEn", "technique"],
    filterFields: { category: "string", active: "boolean" },
    orderBy: { code: "asc" },
    createSchema: finishCreate,
    updateSchema: finishUpdate,
  },
  samples: {
    model: "sample",
    capView: "samples.view",
    capEdit: "samples.edit",
    softDelete: true,
    searchFields: ["sizeLabel", "feedback"],
    filterFields: { status: "string", finishId: "string", contactId: "string", opportunityId: "string" },
    orderBy: { requestedDate: "desc" },
    createSchema: sampleCreate,
    updateSchema: sampleUpdate,
    includeDetail: { finish: true, contact: true, opportunity: true },
  },
  projects: {
    model: "project",
    capView: "projects.view",
    capEdit: "projects.edit",
    capDelete: "projects.delete",
    softDelete: true,
    searchFields: ["code", "name", "city", "address"],
    filterFields: { status: "string", contactId: "string", quotationId: "string", managerId: "string" },
    orderBy: { createdAt: "desc" },
    createSchema: projectCreate,
    updateSchema: projectUpdate,
    includeDetail: {
      contact: { select: { id: true, firstName: true, lastName: true, email: true, phone: true } },
      manager: relatedUser,
      quotation: { select: { id: true, number: true, totalGross: true } },
      serviceType: true,
    },
    sensitiveFields: ["estimatedCost", "contractValue"],
    sensitiveCapability: "projects.financials",
  },
  tasks: {
    model: "projectTask",
    capView: "tasks.view",
    capEdit: "tasks.edit",
    softDelete: true,
    searchFields: ["title", "description"],
    filterFields: { projectId: "string", status: "string", assigneeId: "string" },
    orderBy: [{ dueDate: "asc" }, { position: "asc" }] as never,
    createSchema: taskCreate,
    updateSchema: taskUpdate,
    includeDetail: { assignee: relatedUser, project: { select: { id: true, code: true, name: true } }, dependsOn: { select: { id: true, title: true } } },
  },
  worklogs: {
    model: "workLog",
    capView: "projects.view",
    capEdit: "tasks.edit",
    searchFields: ["note"],
    filterFields: { projectId: "string", userId: "string" },
    orderBy: { date: "desc" },
    createSchema: taskCreate, // replaced by custom upsert route
    updateSchema: taskCreate.partial(),
  },
  changeOrders: {
    model: "changeOrder",
    capView: "projects.view",
    capEdit: "projects.edit",
    searchFields: ["title", "description"],
    filterFields: { projectId: "string", status: "string" },
    orderBy: { createdAt: "desc" },
    createSchema: changeOrderCreate,
    updateSchema: changeOrderCreate.partial(),
    sensitiveFields: ["amount", "cost"],
    sensitiveCapability: "projects.financials",
  },
  events: {
    model: "calendarEvent",
    capView: "calendar.view",
    capEdit: "calendar.edit",
    softDelete: true,
    searchFields: ["title", "location"],
    filterFields: { projectId: "string", assignedUserId: "string", type: "string" },
    orderBy: { start: "asc" },
    createSchema: eventCreate,
    updateSchema: eventUpdate,
    includeDetail: { assignedTo: relatedUser },
  },
  suppliers: {
    model: "supplier",
    capView: "inventory.view",
    capEdit: "inventory.edit",
    softDelete: true,
    searchFields: ["name", "contactName", "email", "vatNumber"],
    filterFields: { active: "boolean" },
    orderBy: { name: "asc" },
    createSchema: supplierCreate,
    updateSchema: supplierUpdate,
  },
  materials: {
    model: "material",
    capView: "inventory.view",
    capEdit: "inventory.edit",
    softDelete: true,
    searchFields: ["code", "nameEl", "nameEn", "category"],
    filterFields: { category: "string", supplierId: "string", active: "boolean" },
    orderBy: { code: "asc" },
    createSchema: materialCreate,
    updateSchema: materialUpdate,
    includeDetail: { supplier: true },
  },
  expenses: {
    model: "expense",
    capView: "finance.view",
    capEdit: "finance.edit",
    softDelete: true,
    searchFields: ["description", "vendor"],
    filterFields: { projectId: "string", category: "string", paid: "boolean" },
    orderBy: { date: "desc" },
    createSchema: expenseCreate,
    updateSchema: expenseUpdate,
    includeDetail: { project: { select: { id: true, code: true, name: true } } },
  },
  payments: {
    model: "payment",
    capView: "finance.view",
    capEdit: "finance.edit",
    softDelete: true,
    searchFields: ["reference", "notes"],
    filterFields: { invoiceId: "string", projectId: "string", contactId: "string", method: "string" },
    orderBy: { paidAt: "desc" },
    createSchema: paymentCreate,
    updateSchema: paymentCreate.partial(),
    includeDetail: { invoice: { select: { id: true, number: true } }, project: { select: { id: true, code: true, name: true } }, contact: { select: { firstName: true, lastName: true } } },
  },
  activities: {
    model: "activity",
    capView: "contacts.view",
    capEdit: "tasks.edit",
    searchFields: ["subject", "body"],
    filterFields: { contactId: "string", companyId: "string", opportunityId: "string", projectId: "string", visitId: "string", kind: "string" },
    orderBy: { occurredAt: "desc" },
    createSchema: activityCreate,
    updateSchema: activityCreate.partial(),
  },
  comments: {
    model: "comment",
    capView: "tasks.view",
    capEdit: "tasks.edit",
    searchFields: ["body"],
    filterFields: { entityType: "string", entityId: "string", resolved: "boolean" },
    orderBy: { createdAt: "desc" },
    createSchema: commentCreate,
    updateSchema: z.object({ resolved: z.boolean() }).partial(),
    includeDetail: { user: { select: { firstName: true, lastName: true, color: true } } },
  },
  serviceTypes: {
    model: "serviceType",
    capView: "dashboard.view",
    capEdit: "settings.system",
    searchFields: ["nameEl", "nameEn"],
    filterFields: { active: "boolean" },
    orderBy: { nameEl: "asc" },
    createSchema: serviceTypeCreate,
    updateSchema: serviceTypeCreate.partial(),
  },
};
